global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
 - job_name: web-apps-stats
   metrics_path: /probe
   params:
     module: [http_2xx]
   static_configs:
     - targets:
       - https://nginx:443/prometheus
       - https://nginx:443/dbms/status
       - https://nginx:443/departments/status
       - https://nginx:443/employees/status
       - https://nginx:443
   relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
 - job_name: 'node-stats'
   metrics_path: /probe
   params:
     module: [tcp_connect]
   static_configs:
     - targets:
       - blackbox-exporter:9115
       - prometheus:9090
       - dbms:5000
       - departments:5000
       - employees:5000
       - nginx:443
   relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.